---
- name: Configure Elastic APT key
  apt_key: url=https://packages.elastic.co/GPG-KEY-elasticsearch
           state=present

- name: Configure the Elastic APT repositories
  apt_repository: repo="deb http://packages.elastic.co/logstash/{{ logstash_short_version }}/debian stable main"
                  state=present

- name: Install Logstash
  apt: pkg="logstash={{ logstash_version }}"
       state=present

- name: Enable the Logstash service
  service: name=logstash enabled=yes
